version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lanchonete_user
      - POSTGRES_PASSWORD=lanchonete_password
      - POSTGRES_DB=lanchonete
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
