apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-configmap
  namespace: lanchonete
  labels:
    app: cm-postgres
data:
  PG_HOST: "terraform-20241216005549066300000002.cn4si460a9sw.us-east-1.rds.amazonaws.com"