apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
  namespace: lanchonete
  labels:
    app: ds-lanchonete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ds-lanchonete
  template:
    metadata:
      labels:
        app: ds-lanchonete
    spec:
      containers:
        - name: lanchonete
          image: tiagogn/lanchonete:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1024Mi"   # Limite de memória que o container pode usar
              cpu: "1000m"       # Limite de CPU
            requests:
              memory: "512Mi"   # Quantidade mínima de memória necessária
              cpu: "250m"       # Quantidade mínima de CPU necessária
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prd"
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-configmap
                  key: PG_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: "lanchonete"
          readinessProbe:
            httpGet:
              path: /lanchonete/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /lanchonete/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20