apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
  namespace: lanchonete
spec:
  selector:
    app: ds-lanchonete
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort