apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lanchonete-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lanchonete-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80 # Escalará quando a utilização de CPU atingir 80%