spring:
  profiles:
    active: ${springProfile:local}
  application:
    name: lanchonete
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
server:
  servlet:
    context-path: /lanchonete

