spring:
  profiles:
    active: ${springProfile:local}
  application:
    name: lanchonete
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lanchonete
    username: lanchonete_user
    password: lanchonete_password
  flyway:
    enabled: true
server:
  servlet:
    context-path: /lanchonete

