apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: lanchonete
  labels:
    type: local
    app: pv-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: lanchonete
  labels:
    app: pvc-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi