apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: lanchonete
  labels:
    app: ds-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-postgres
  template:
    metadata:
      labels:
        app: ds-postgres
    spec:
      containers:
        - name: ds-postgres
          image: postgres:16
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-dbname
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: postgres-pv-claim