apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lanchonete
  labels:
    app: svc-postgres
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: ds-postgres